version: "3.8"
services:
    php:
        environment:
            - PHP_VERSION=8.1
            - LAMBDA_HANDLER_FUNCTION=${LAMBDA_HANDLER_FUNCTION}
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - LAMBDA_HANDLER_FUNCTION=${LAMBDA_HANDLER_FUNCTION}
        image: tiagofranca/base-aws-php:latest
        ports:
            - ${LAMBDA_OFFLINE_LOCAL_PORT:-9000}:8080
        volumes:
            - ./.docker-data/php/custom-options.ini:/etc/php.d/20-custom-options.ini:cached
            - .:/var/task:cached
            - .docker-data/bash_users/root:/root:cached

        ## É o equivalente a 'CMD' no Dockerfile
        ## Caso vazio, executará o que está definido no CMD do Dockerfile
        command: ${LAMBDA_HANDLER_FUNCTION}
